config/routes.rb
Rails.application.routes.draw do

  get '/zipcode', to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'  
  post 'zipcode' => 'home#zipcode'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
   def index
  #   require 'net/http'
  #   require 'json'
  #   @url = 'http://www.airnowapi.org/aq/observation/zipCode/current/?format=application/json&zipCode=' + @zip_query.to_s + '&distance=25&API_KEY=10527081-FDE1-4CF9-8630-B58F2BEBAED5'
  #   @uri = URI(@url)
  #   @response = Net::HTTP.get(@uri)
  #   @output = JSON.parse(@response)

  #     if @output.empty?
  #       @myerrormsg = "Please Enter a ZipCode"
  #       else        
  #       @final_output = @output
  #       @myAQI = @final_output[0]['AQI']
  #       case @myAQI
  #         when 1..50
  #           @api_color = "green"
  #         when 51..100
  #           @api_color = "yellow"
  #         when 101..150
  #           @api_color = "orange"
  #         when 151..200
  #           @api_color = "red"
  #         when 201..300
  #           @api_color = "purple"
  #         when 301..500
  #           @api_color = "maroon"
  #         else
  #           @api_color = "pink"
  #         end
  #     end
     end
      
    def zipcode
      @zip_query = params[:zipcode]
      if params{:zipcode} == ""
        @zip_query = "Please enter a zipcode"
      else params[:zipcode]
        require 'net/http'
        require 'json'
        require 'date'
        current_time = Time.now                
        @Now = current_time.strftime("%m/%d/%y %l:%M %p")
        @url = 'http://www.airnowapi.org/aq/observation/zipCode/current/?format=application/json&zipCode=' + @zip_query.to_s + '&distance=25&API_KEY=10527081-FDE1-4CF9-8630-B58F2BEBAED5'
        @uri = URI(@url)
        @response = Net::HTTP.get(@uri)
        @output = JSON.parse(@response)
    
          if @output.empty?
            @myerrormsg = "There was an error retrieving data"
          else        
            @final_output = @output
            @myAQI = @final_output[0]['AQI']
          case @myAQI
            when 1..50
              @api_color = "green"
            when 51..100
              @api_color = "yellow"
            when 101..150
              @api_color = "orange"
            when 151..200
              @api_color = "red"
            when 201..300
              @api_color = "purple"
            when 301..500
              @api_color = "maroon"
            else
              @api_color = "pink"
            end
          end
      end      
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/OLDIndex.html.erb
<div class="jumbotron <%= @api_color %>">
  <h1 class="display-4">
  <% if @output.empty? %>
    <%= @myerrormsg %>
  <%  else %>
    Air Quality Index: <%= @final_output[0]['AQI'] %> </br>
    Reporting Area: <%= @final_output[0]['ReportingArea'] %></br>
    Category Number: <%= @final_output[0]['Category']['Number']%> </br>
    Date Observed: <%= @final_output[0]['DateForecast'] %></br>
    </h1>
      <p class="lead">This is the current Air Quality Score for <%= @final_output[0]['ReportingArea']%>, <%= @final_output[0]['StateCode']%>: <%= @final_output[0]['AQI'] %></p>
      <hr class="my-4">
      <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
      <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
  </div>

    <% @output %>
  <% end %>

app/views/home/index.html.erb
<div class="jumbotron <%= @api_color %>">
  <h1 class="display-4">
  Lookup the Air Quality Score  
  </h1>
</div>

app/views/home/zipcode.html.erb
<div class="jumbotron <%= @api_color %>">
  <h1 class="display-4">
    <% if @output.empty? %>
    <id="MyError">
        <%= @myerrormsg %>
    <% else %>
      Air Quality Index: <%= @final_output[0]['AQI'] %> </br>
      Reporting Area: <%= @final_output[0]['ReportingArea'] %></br>
      Category Number: <%= @final_output[0]['Category']['Number']%> </br>
      Date Observed: <%= @final_output[0]['DateObserved'] %></br>
      Current Time: <%= @Now %>
  </h1>
        <p class="lead">This is the current Air Quality Score for <%= @final_output[0]['ReportingArea']%>, <%= @final_output[0]['StateCode']%>: <%= @final_output[0]['AQI'] %></p>
        <hr class="my-4">
    <% end %> 
  </div>  
</br>
  

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Air Quality', root_path, class:"navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Weather Forecast <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>     
      <%= form_tag zipcode_path, :method => 'POST' do %>
        <div class="form-inline my-2 my-lg-0">
          <%= text_field_tag 'zipcode', nil, placeholder: "Search ZipCode", class: "form-control mr-sm-2" %>
          <%= submit_tag 'Search', class: 'btn btn-outline-secondary my-2 my-sm-0'%>
        </div>
      <% end %>            
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirQuality</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="container">
      </br> 
      <%= yield %>
    </div>
  </body>
</html>